version: "3.1"
services:
  m4tv2:
    build: 
      context: ./
    container_name: m4tv2
    # environment:
    #   - CHECKPOINTS_PATH=/root/models
    #   - GRADIO_SERVER_NAME=0.0.0.0
    ports:
      - 7860:7860
    # volumes:
    #   - ./volumes/checkpoints:/opt/fish-speech/checkpoints
    #   - ./volumes/references:/opt/fish-speech/references
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              count: all
              capabilities: [gpu]
