version: "3.1"
services:
  m4tv2:
    build: 
      context: ./
    container_name: m4tv2
    environment:
      - CHECKPOINTS_PATH=/home/root/app/models
      - GRADIO_SERVER_NAME=0.0.0.0
      # - https_proxy=http://127.0.0.1:7777
    ports:
      - 7860:7860
    volumes:
      - ./models:/home/root/app/models:rw
      - ./seamless_communication:/home/seamless_communication:rw
    # deploy:
    #   resources:
    #     reservations:
    #       devices:
    #         - driver: nvidia
    #           count: all
    #           capabilities: [gpu]
